apiVersion: v1
kind: ConfigMap
metadata:
  name: extension-apiserver-authentication
  namespace: kube-system
data:
  client-ca-file: /etc/kubernetes/kube.sayyidyofa.me.crt
  requestheader-client-ca-file: /etc/kubernetes/kube.sayyidyofa.me.crt
  # These are the standard header configurations for the extension API server
  #requestheader-allowed-names: '[]'
  #requestheader-extra-headers-prefix: '["X-Remote-Extra-"]'
  #requestheader-group-headers: '["X-Remote-Group"]'
  #requestheader-username-headers: '["X-Remote-User"]'