- name: Set Up Control Plane Nodes
  hosts: control-plane
  become: true

  vars:
    etcd_version: 1
    kubernetes_version: 1

  tasks:
    - name: get ip address
      shell:
        cmd: ip a  

- name: Setup Worker Nodes
  hosts: worker
  become: true

  tasks:
    - name: get ip address
      shell:
        cmd: ip a  
